# Generated by Django 3.2.13 on 2022-07-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
