# Generated by Django 3.2.13 on 2022-07-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
    ]
