# Generated by Django 3.2.13 on 2022-07-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_products_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SOLD', 'Sold')], default='PENDING', max_length=20),
        ),
    ]
